### ISSUE TITLE
This is broken, any to fix?

### ISSUE THREAD

**Issue by dboeckenhoff** [dls-controls/sphinx-apischema#3]
Sphinx parallel build error:
sphinx.errors.ExtensionError: Handler <function process_docstring at 0x7f294762b370> for event 'autodoc-process-docstring' threw an exception (exception: 'str' object has no attribute 'get')

**Comment by coretl** [comment]
Unfortunately we have migrated all our projects from apischema to pydantic, so no longer maintain this extension. I will archive the repository to make this clear.
